// Generated by https://pagedraw.io/pages/9799
import Boardline from './boardline';
import React from 'react';
import './board.css';

function render() {
    return <div className="board-board-0">
        <div className="board-0">
            <div className="board-boardline_instance-3">
                <Boardline xPosition={0} states={(this.props.states[0])} boardValues={(this.props.board[0])} handleClick={this.props.handleClick} /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}