// Generated by https://pagedraw.io/pages/9799
import Boardline from './boardline';
import React from 'react';
import './board.css';

function render() {
    return <div className="board-board-0">
        <div className="board-0">
            <div className="board-0-0">
                <div className="board-0-0-0">
                    <div className="board-remaining_bombs_label-5">
                        {"Remaining Bombs: "}
                    </div>
                </div>
            </div>
            <div className="board-0-1">
                <div className="board-0-1-0">
                    <div className="board-remaining_bombs_count-0">
                        { this.props.remainingBombs }
                    </div>
                </div>
            </div>
            <div onClick={this.props.flagClick} className="board-flag_mode_button-0" style={{"background": this.props.flagButtonColor}}>
                <div className="board-0-2-0">
                    <img src="https://ucarecdn.com/88771d9f-a64b-404f-a959-3caebac55674/" className="board-flag_icon-8" /> 
                </div>
            </div>
        </div>
        <div className="board-1">
            <div className="board-game_board-9">
                <div className="board-1-0-0">
                    <div className="board-boardline_0">
                        <Boardline xPosition={0} states={(this.props.states[0])} boardValues={(this.props.board[0])} handleClick={this.props.handleClick} /> 
                    </div>
                </div>
                <div className="board-1-0-1">
                    <div className="board-boardline_1">
                        <Boardline xPosition={1} states={(this.props.states[1])} boardValues={(this.props.board[1])} handleClick={this.props.handleClick} /> 
                    </div>
                </div>
                <div className="board-1-0-2">
                    <div className="board-boardline_2">
                        <Boardline xPosition={2} states={(this.props.states[2])} boardValues={(this.props.board[2])} handleClick={this.props.handleClick} /> 
                    </div>
                </div>
                <div className="board-1-0-3">
                    <div className="board-boardline_3">
                        <Boardline xPosition={3} states={(this.props.states[3])} boardValues={(this.props.board[3])} handleClick={this.props.handleClick} /> 
                    </div>
                </div>
                <div className="board-1-0-4">
                    <div className="board-boardline_4">
                        <Boardline xPosition={4} states={(this.props.states[4])} boardValues={(this.props.board[4])} handleClick={this.props.handleClick} /> 
                    </div>
                </div>
                <div className="board-1-0-5">
                    <div className="board-boardline_5">
                        <Boardline xPosition={5} states={(this.props.states[5])} boardValues={(this.props.board[5])} handleClick={this.props.handleClick} /> 
                    </div>
                </div>
                <div className="board-1-0-6">
                    <div className="board-boardline_6">
                        <Boardline xPosition={6} states={(this.props.states[6])} boardValues={(this.props.board[6])} handleClick={this.props.handleClick} /> 
                    </div>
                </div>
                <div className="board-1-0-7">
                    <div className="board-boardline_7">
                        <Boardline xPosition={7} states={(this.props.states[7])} boardValues={(this.props.board[7])} handleClick={this.props.handleClick} /> 
                    </div>
                </div>
                <div className="board-1-0-8">
                    <div className="board-boardline_8">
                        <Boardline xPosition={8} states={(this.props.states[8])} boardValues={(this.props.board[8])} handleClick={this.props.handleClick} /> 
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}