// Generated by https://pagedraw.io/pages/9799
import Square from './square';
import React from 'react';
import './boardline.css';

function render() {
    return <div className="boardline-boardline-9">
        <div className="boardline-0">
            <div className="boardline-square_instance_2">
                <Square state={(this.props.states[0])} color={"#ffffff"} xPosition={this.props.xPosition} yPosition={0} handleClick={this.props.handleClick} boardValue={(this.props.boardValues[0])} /> 
            </div>
            <div className="boardline-square_instance_2-9">
                <Square state={(this.props.states[0])} color={"#ffffff"} xPosition={this.props.xPosition} yPosition={0} handleClick={this.props.handleClick} boardValue={(this.props.boardValues[0])} /> 
            </div>
            <div className="boardline-square_instance_2-6">
                <Square state={(this.props.states[0])} color={"#ffffff"} xPosition={this.props.xPosition} yPosition={0} handleClick={this.props.handleClick} boardValue={(this.props.boardValues[0])} /> 
            </div>
            <div className="boardline-square_instance_2-4">
                <Square state={(this.props.states[0])} color={"#ffffff"} xPosition={this.props.xPosition} yPosition={0} handleClick={this.props.handleClick} boardValue={(this.props.boardValues[0])} /> 
            </div>
            <div className="boardline-square_instance_2-91">
                <Square state={(this.props.states[0])} color={"#ffffff"} xPosition={this.props.xPosition} yPosition={0} handleClick={this.props.handleClick} boardValue={(this.props.boardValues[0])} /> 
            </div>
            <div className="boardline-square_instance_2-0">
                <Square state={(this.props.states[0])} color={"#ffffff"} xPosition={this.props.xPosition} yPosition={0} handleClick={this.props.handleClick} boardValue={(this.props.boardValues[0])} /> 
            </div>
            <div className="boardline-square_instance_2-7">
                <Square state={(this.props.states[0])} color={"#ffffff"} xPosition={this.props.xPosition} yPosition={0} handleClick={this.props.handleClick} boardValue={(this.props.boardValues[0])} /> 
            </div>
            <div className="boardline-square_instance_2-1">
                <Square state={(this.props.states[0])} color={"#ffffff"} xPosition={this.props.xPosition} yPosition={0} handleClick={this.props.handleClick} boardValue={(this.props.boardValues[0])} /> 
            </div>
            <div className="boardline-square_instance_2-40">
                <Square state={(this.props.states[0])} color={"#ffffff"} xPosition={this.props.xPosition} yPosition={0} handleClick={this.props.handleClick} boardValue={(this.props.boardValues[0])} /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}