// Generated by https://pagedraw.io/pages/9799
import MinesweeperController from '../MinesweeperController';
import Board from './board';
import React from 'react';
import './mainscreen.css';

function render() {
    return <div className="mainscreen-mainscreen-8">
        <div className="mainscreen-0">
            <div className="mainscreen-board_instance-1">
                <MinesweeperController />
            </div>
        </div>
        <div className="mainscreen-1" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}